#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "trusty_scribe_viewer.settings")
    try:
        repo_path = sys.argv[1]
    except IndexError:
        repo_path = '.'
    os.environ.setdefault("REPOPATH", repo_path)
    from django.core.management import execute_from_command_line
    execute_from_command_line(['tsv', 'runserver'])
